//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp20
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оборудование
    {
        public Оборудование()
        {
            this.Операции = new HashSet<Операции>();
        }
    
        public int ID_Оборудования { get; set; }
        public string Название_ { get; set; }
        public string Модель { get; set; }
        public string Серийный_номер { get; set; }
        public string Статус { get; set; }
        public System.DateTime Дата_покупки { get; set; }
        public string Срок_службы { get; set; }
    
        public virtual ICollection<Операции> Операции { get; set; }
    }
}
