//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp20
{
    using System;
    using System.Collections.Generic;
    
    public partial class Операции
    {
        public int ID_Операции { get; set; }
        public string Тип_операции { get; set; }
        public System.DateTime Дата_операции { get; set; }
        public Nullable<int> ID_Оборудования { get; set; }
        public Nullable<int> ID_Сотрудника { get; set; }
        public Nullable<int> ID_Поставщика { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<int> Стоимость { get; set; }
        public string Описание { get; set; }
        public string photo { get; set; }
    
        public virtual Оборудование Оборудование { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Поставщики Поставщики { get; set; }
    }
}
