//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp20
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставщики
    {
        public Поставщики()
        {
            this.Операции = new HashSet<Операции>();
        }
    
        public int ID_Поставщика { get; set; }
        public string Название_поставщика_ { get; set; }
        public string Адрес { get; set; }
        public string Телефон { get; set; }
    
        public virtual ICollection<Операции> Операции { get; set; }
    }
}
